# Generated by Django 6.0.5 on 2026-08-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Sent'), ('not_needed', 'No Longer Needed'), ('size_issue', 'Size/Fit Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='crud.order')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
    ]
