# Generated by Django 6.0.5 on 2026-08-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('damaged', 'Damaged Product'), ('lost', 'Lost in Transit'), ('missing_item', 'Missing Item'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='open', max_length=20)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('filed_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='crud.order')),
            ],
            options={
                'ordering': ['-filed_date'],
            },
        ),
    ]
