# Generated by Django 6.0.5 on 2026-08-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_catalogupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zip_file', models.FileField(upload_to='image_bulk_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('processed_images', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
    ]
