# Generated by Django 6.0.5 on 2026-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_imagebulkupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=50)),
                ('inspector_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('rework', 'Rework')], default='pending', max_length=20)),
                ('defect_count', models.PositiveIntegerField(default=0)),
                ('inspection_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Quality checks',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
