# Generated by Django 6.0.5 on 2026-08-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['product'], 'verbose_name_plural': 'inventory'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='product_name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='crud.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crud.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pricings', to='crud.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quality',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='crud.product'),
            preserve_default=False,
        ),
    ]
