# Generated by Django 6.0.5 on 2026-08-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_warehouse_remove_inventory_warehouse_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('other', 'Other')], default='instagram', max_length=20)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('campaign_name', models.CharField(max_length=150)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencer_campaigns', to='crud.product')),
            ],
            options={
                'verbose_name': 'Influencer campaign',
                'verbose_name_plural': 'Influencer campaigns',
                'ordering': ['-start_date'],
            },
        ),
    ]
