# Generated by Django 6.0.5 on 2026-08-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogupload',
            name='category',
            field=models.CharField(choices=[('gowns_ethnic', 'Gowns - Ethnic'), ('top_bottom_sets', 'Top & Bottom Sets'), ('kurti_dupatta', 'Kurti With Dupatta'), ('kurtis', 'Kurtis'), ('sarees', 'Sarees'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='catalogupload',
            name='upload_type',
            field=models.CharField(choices=[('bulk', 'Bulk Upload'), ('single', 'Single Upload')], default='bulk', max_length=10),
        ),
    ]
