# Generated by Django 6.0.5 on 2026-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_catalogupload_category_catalogupload_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % e.g. 18.00', max_digits=5),
        ),
    ]
