# Generated by Django 6.0.5 on 2026-08-12 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_product_gst_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('compensation', 'Compensation'), ('recovery', 'Recovery')], default='compensation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayoutCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('sales_returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ads_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neft_id', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cycle_date'],
            },
        ),
    ]
