# Generated by Django 6.0.5 on 2026-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0020_compensationrecovery_payoutcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('account_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=20)),
                ('panel_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
