# Generated by Django 6.0.5 on 2026-08-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_callbackrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('promotion_type', models.CharField(choices=[('sale_event', 'Sale Event'), ('flexi_growth', 'Flexi Growth Offer'), ('deal', 'Deal'), ('flash_event', 'Flash Event')], default='sale_event', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('expired', 'Expired')], default='upcoming', max_length=20)),
                ('participation_status', models.CharField(choices=[('open', 'Open for Participation'), ('participating', 'Participating'), ('closed', 'Closed')], default='open', max_length=20)),
                ('orders_multiplier', models.PositiveIntegerField(default=1, help_text="e.g. 10 for 'Upto 10 times more orders'")),
                ('views_multiplier', models.PositiveIntegerField(default=1, help_text="e.g. 10 for 'Upto 10 times more views'")),
                ('expected_customers_crores', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_day_to_join', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
