# Generated by Django 6.0.5 on 2026-08-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_migrate_legacy_categories'),
        ('shop', '0005_alter_category_options_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crud_products', to='shop.supplierprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='legacy_category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen'), ('beauty', 'Beauty'), ('grocery', 'Grocery'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
