# Generated by Django 6.0.5 on 2026-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0029_product_supplier_alter_product_legacy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('user', 'User')], default='staff', max_length=20),
        ),
    ]
