# Generated by Django 6.0.5 on 2026-08-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('whatsapp_notifications_enabled', models.BooleanField(default=True)),
                ('bank_account_holder', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('signature_text', models.CharField(blank=True, max_length=150)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
