# Generated by Django 6.0.5 on 2026-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_options_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_mode', models.CharField(choices=[('single', 'Single Category (Clothes only)'), ('multiple', 'Multiple Category')], default='multiple', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
